name: Auto Replace Path in README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  replace-path:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Replacer Script
        run: python3 .gitaction/replacer.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "auto-replace README snake image path [skip ci]" || exit 0
          git push